[package]
name = "tnt-number-field"
version = "0.1.0"
authors = ["Matthew Torrence <matt@torrencefamily.net>"]
edition = "2018"

[dependencies]
tnt-polynomial = { path = "../polynomial" }
tnt-alg = { path = "../alg" }
static_assertions = "1.1.0"
