[package]
name = "runt"
version = "0.1.0"
authors = ["Matthew Torrence <matt@torrencefamily.net>"]
edition = "2018"

[workspace]
members = [
    "crates/runt-alg",
    "crates/runt-polynomial",
    "crates/runt-number-field",
]

[dependencies]
