[package]
name = "tnt-alg"
version = "0.1.0"
authors = ["Matthew Torrence <matt@torrencefamily.net>"]
edition = "2018"

[dependencies]
num-traits = "0.2.14"
static_assertions = "1.1.0"
ramp = "0.5.9"
ordered-float = "2.0.1"
