[package]
name = "runt-number-field"
version = "0.1.0"
authors = ["Matthew Torrence <matt@torrencefamily.net>"]
edition = "2018"

[dependencies]
runt-polynomial = { path = "../runt-polynomial" }
runt-alg = { path = "../runt-alg" }
static_assertions = "1.1.0"
