[package]
name = "runt-polynomial"
version = "0.1.0"
authors = ["Matthew Torrence <matt@torrencefamily.net>"]
edition = "2018"

[dependencies]
runt-alg = { path = "../runt-alg" }
num-traits = "0.2.14"
